### ISSUE TITLE
Move from cryptonite to crypton

### ISSUE THREAD

**Issue by ocramz** [ocheron/cryptostore#10]
Apparently 'cryptonite' is not actively maintained, and 'crypton' is the new standard.

A number of key networking libraries have switched to 'crypton' already : https://packdeps.haskellers.com/reverse/crypton

It's API-compatible, so this should be just an import renaming chore.

**Comment by ocheron** [comment]
I worked to add a cabal flag but this is apparently too early, the new packages are not even on stackage nightly because of build errors.

**Comment by ocheron** [comment]
Added flag `use_crypton` to let users choose.

**Comment by ocramz** [comment]
@ocheron thank you for looking at this so quickly!
