### ISSUE TITLE
Migrate to crypton?

### ISSUE THREAD

**Issue by epoberezkin** [ocheron/cryptostore#11]
@ocheron are you by any chance planning to migrate it to [crypton](https://github.com/kazu-yamamoto/crypton)?

I can make a PR.

I was trying to switch to crypton 0.34 when I realised that we use this package...

cc @kazu-yamamoto

**Comment by epoberezkin** [comment]
found the flag :)

**Comment by kazu-yamamoto** [comment]
@epoberezkin  ocheron also left from the Haskell community.

**Comment by epoberezkin** [comment]
we'll call it sabbatical
