### ISSUE TITLE
`crypton` support?

### ISSUE THREAD

**Issue by goertzenator** [ocheron/cryptostore#12]
This library has been very useful to me; I use it with `tls` to output certificates.  However `tls` has moved on from `x509` to `crypton-x509`, but this library only works with `x509`.  I would like to request `crypton` support.  I don't know if that can be integrated here or if it should be a fork.

**Comment by ocheron** [comment]
Great to read it's useful.
The library has support for `crypton` through optional flag `use_crypton`.
I don't plan to make it default at this point.

**Comment by goertzenator** [comment]
I missed that, thank you!  For other readers landing here I added this to `cabal.project`:

```
constraints:
  cryptostore +use_crypton
```
