### ISSUE TITLE
Creating a password-protected p12 file

### ISSUE THREAD

**Issue by eyeinsky** [ocheron/cryptostore#4]
Hi! I was skimming on how to save a password-protected P12 file and have the following question: the `writeP12FileToMemory` takes a password as one of its arguments, and so does `encrypted` -- do the passwords need to be the same (because the container is decrypted and then re-encrypted on creating the byte string), or will the container have two passwords is the end (and I should skip one of these to get just one)?

**Comment by ocheron** [comment]
Usually passwords given to both functions will be the same.
Not all software can handle integrity password and encryption password to be different.

**Comment by eyeinsky** [comment]
Thank you for clearing that up!
